# Generated by Django 5.0.6 on 2024-07-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buzos',
            new_name='buzo',
        ),
        migrations.RenameModel(
            old_name='shirts',
            new_name='pant',
        ),
        migrations.RenameModel(
            old_name='pants',
            new_name='shirt',
        ),
        migrations.RenameField(
            model_name='pant',
            old_name='modelo_shirt',
            new_name='modelo_pant',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='modelo_pant',
            new_name='modelo_shirt',
        ),
    ]
